services:
  - type: web
    name: websage-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
